#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC3043

USE_PROCD=1
START=99

start_service() {
    config_load dhcp-snooper

    local enabled
    config_get_bool enabled "main" "enabled" "1"
    [ "$enabled" -eq "1" ] || return 0

    procd_open_instance
    procd_set_param command /usr/bin/dhcp-snooper
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "dhcp-snooper"
}
